version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_sowadb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
